name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        python-version:
          - 3.11.0
          - 3.10.0
          - 3.9.0
          - 3.8.0
          - 3.7.1
          - 3.6.7
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: '${{ matrix.python-version }}'
      - name: "Install python dependencies"
        run: |
          pip install ".[dev]"
      - name: "Run tests"
        run: |
          pytest test.py --cov
      - uses: codecov/codecov-action@v3
